"""Independent Bollinger Evolver package skeleton.

This package is intentionally isolated from the existing GeneTrader runtime.
It provides placeholders for future Bollinger-specific evolution logic,
configuration loading, reporting, and test coverage.
"""

from .config_loader import (
    BollingerConfigError,
    REQUIRED_FIELDS,
    load_bollinger_config,
    validate_bollinger_config,
)
from .data_quality import evaluate_data_coverage_gate
from .evaluators import (
    DEFAULT_EVALUATION_DIR,
    FitnessConfig,
    FitnessResult,
    build_backtest_params,
    compute_fitness_score,
    evaluate_candidate,
    normalize_backtest_metrics,
    sanitize_mapping,
    write_evaluation_artifact,
)
from .ga import (
    DEFAULT_BEST_DIR,
    DEFAULT_GENERATION_DIR,
    GAOrchestratorConfig,
    GAOrchestratorResult,
    GASessionConfig,
    GASessionResult,
    GenerationConfig,
    GenerationResult,
    IndividualEvaluation,
    BacktestEvaluationAdapter,
    MockStrategyEvaluator,
    PositionSizingSmokeEvaluator,
    SmokeRunConfig,
    build_next_population,
    calculate_basic_backtest_fitness,
    build_deterministic_mock_metrics,
    build_position_sizing_snapshot,
    build_smoke_initial_population,
    candidate_id,
    crossover_candidates,
    extract_gene_snapshot,
    evaluate_individual_with_mock_pipeline,
    initialize_population,
    mock_fitness_from_metrics,
    mutate_candidate,
    normalize_candidate_genes,
    run_generation,
    run_ga,
    run_ga_session,
    run_smoke_ga_pipeline,
    render_session_report,
    select_elites,
    write_best_candidate,
    write_generation_summary,
)

__all__ = [
    "BollingerConfigError",
    "REQUIRED_FIELDS",
    "load_bollinger_config",
    "validate_bollinger_config",
    "evaluate_data_coverage_gate",
    "DEFAULT_EVALUATION_DIR",
    "FitnessConfig",
    "FitnessResult",
    "build_backtest_params",
    "compute_fitness_score",
    "evaluate_candidate",
    "normalize_backtest_metrics",
    "sanitize_mapping",
    "write_evaluation_artifact",
    "DEFAULT_BEST_DIR",
    "DEFAULT_GENERATION_DIR",
    "GAOrchestratorConfig",
    "GAOrchestratorResult",
    "GASessionConfig",
    "GASessionResult",
    "GenerationConfig",
    "GenerationResult",
    "IndividualEvaluation",
    "BacktestEvaluationAdapter",
    "MockStrategyEvaluator",
    "PositionSizingSmokeEvaluator",
    "SmokeRunConfig",
    "build_next_population",
    "calculate_basic_backtest_fitness",
    "build_deterministic_mock_metrics",
    "build_position_sizing_snapshot",
    "build_smoke_initial_population",
    "candidate_id",
    "crossover_candidates",
    "extract_gene_snapshot",
    "evaluate_individual_with_mock_pipeline",
    "initialize_population",
    "mock_fitness_from_metrics",
    "mutate_candidate",
    "normalize_candidate_genes",
    "run_generation",
    "run_ga",
    "run_ga_session",
    "run_smoke_ga_pipeline",
    "render_session_report",
    "select_elites",
    "write_best_candidate",
    "write_generation_summary",
]
